 ## Numpy - Data Analysis 
### One dimension array 

In [5]:
## libraries 

In [1]:
numbers =[1,3,7,8,9,4,3,]

In [2]:
numbers

[1, 3, 7, 8, 9, 4, 3]

In [3]:
type (numbers)

list

In [4]:
 len (numbers)

7

In [6]:
import numpy

In [8]:
num=numpy.array(numbers)

In [9]:
num

array([1, 3, 7, 8, 9, 4, 3])

In [10]:
type (num )

numpy.ndarray

In [11]:
import numpy as np


In [12]:
b=np.array([1,2,3,4,5])

In [13]:
b

array([1, 2, 3, 4, 5])

In [14]:
b.shape 

(5,)

In [15]:
b

array([1, 2, 3, 4, 5])

In [16]:
b.min()

1

In [17]:
b.max()

5

In [18]:
b.mean()

3.0

In [19]:
b.std()

1.4142135623730951

In [20]:
b.var ()

2.0

In [21]:
b 

array([1, 2, 3, 4, 5])

In [22]:
d=np.array([1,2])
f=np.array([2,2])

In [23]:
d*f

array([2, 4])

In [24]:
d+f

array([3, 4])

In [25]:
d-f

array([-1,  0])

In [26]:
d/f

array([0.5, 1. ])

In [27]:
f/d

array([2., 1.])